### ISSUE TITLE
Set color & width of  "unused" filter

### ISSUE THREAD

**Issue by chrislaurie-io** [shirne/progress_border#1]
I use the progress border to either show a thin (1 pixel) border or the progress  border. When the progress border is active then it works fine except the existing border disappears. I would like to set the width and color of the "remainder / unused" portion of the border.

**Comment by shirne** [comment]
https://github.com/shirne/progress_border/commit/6eb43bff9b2e39016aea4ca44c9f27f2f01c7de8

Add backgroundBorder for paint a complete border under progress border.

**Comment by shirne** [comment]
@chrislaurie-bs Does this feature meet your needs?

**Comment by chrislaurie-io** [comment]
@shirne That is perfect! Thank you. This is a great package.
